language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-mint-ionic' ]; then cd .. && eval "mv $currentfolder generator-mint-ionic" && cd generator-mint-ionic; fi
